# Generated by Django 5.2.11 on 2026-02-25 08:30

from django.db import migrations
from slugify import slugify

CATEGORIES = [
    "Бутерброды и сендвичи",
    "Горячие блюда",
    "Дополнения",
    "Завтраки и яичница",
    "Каши и сладкие завтраки",
    "Коктейли",
    "Кофе",
    "Не кофе",
    "Салаты и закуски",
    "Холодный кофе",
]


def seed_categories(apps, schema_editor):
    Category = apps.get_model("menu", "Category")

    existing = set(Category.objects.values_list("slug", flat=True))
    order = Category.objects.count()

    for name in CATEGORIES:
        slug = slugify(name)
        if slug in existing:
            continue
        order += 1
        Category.objects.create(
            name=name,
            slug=slug,
            order=order,
        )
        existing.add(slug)


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_categories, migrations.RunPython.noop),
    ]