# Generated by Django 5.2.11 on 2026-04-19 17:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0002_seed_categories"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["order", "name"],
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.AlterModelOptions(
            name="item",
            options={
                "ordering": ["order", "name"],
                "verbose_name": "Позиция меню",
                "verbose_name_plural": "Позиции меню",
            },
        ),
        migrations.AddField(
            model_name="item",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="category",
            name="name_en",
            field=models.CharField(max_length=200, null=True, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="category",
            name="name_ru",
            field=models.CharField(max_length=200, null=True, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="category",
            name="name_tk",
            field=models.CharField(max_length=200, null=True, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="category",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=0, verbose_name="Порядок"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="menu.category",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="item",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="item",
            name="description_ru",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="item",
            name="description_tk",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="item",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="menu/items/",
                verbose_name="Изображение",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="is_new",
            field=models.BooleanField(default=False, verbose_name="Новинка"),
        ),
        migrations.AlterField(
            model_name="item",
            name="is_seasonal",
            field=models.BooleanField(default=False, verbose_name="Сезонное"),
        ),
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="item",
            name="name_en",
            field=models.CharField(max_length=200, null=True, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="item",
            name="name_ru",
            field=models.CharField(max_length=200, null=True, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="item",
            name="name_tk",
            field=models.CharField(max_length=200, null=True, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="item",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=0, verbose_name="Порядок"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Цена",
            ),
        ),
    ]
