# Generated by Django 5.2.11 on 2026-05-01 12:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0003_alter_category_options_alter_item_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoastedCoffee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                (
                    "origin",
                    models.CharField(blank=True, max_length=200, verbose_name="Страна"),
                ),
                (
                    "region",
                    models.CharField(blank=True, max_length=200, verbose_name="Регион"),
                ),
                (
                    "weight",
                    models.CharField(
                        blank=True,
                        help_text="Например: 250g",
                        max_length=50,
                        verbose_name="Вес",
                    ),
                ),
                (
                    "flavor_notes",
                    models.TextField(blank=True, verbose_name="Букет вкуса"),
                ),
                (
                    "brew_method",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Способ приготовления"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Цена",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="roasted/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="Порядок"
                    ),
                ),
            ],
            options={
                "verbose_name": "Обжаренный кофе",
                "verbose_name_plural": "Обжаренный кофе",
                "ordering": ["order", "name"],
            },
        ),
    ]
