# Generated by Django 5.2.11 on 2026-07-22 08:40

import django.db.models.deletion
from django.db import migrations, models


def link_categories_to_default_venue(apps, schema_editor):
    Venue = apps.get_model("menu", "Venue")
    Category = apps.get_model("menu", "Category")

    if not Category.objects.filter(venue__isnull=True).exists():
        return

    venue, _ = Venue.objects.get_or_create(
        slug="kakao",
        defaults={"name": "Какао"},
    )
    Category.objects.filter(venue__isnull=True).update(venue=venue)


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_venue_alter_category_slug_alter_item_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='menu.venue', verbose_name='Заведение'),
        ),
        migrations.RunPython(link_categories_to_default_venue, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='category',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='menu.venue', verbose_name='Заведение'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('venue', 'slug')},
        ),
    ]
