# Generated by Django 5.2.11 on 2026-07-22 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_venue_alter_category_slug_alter_item_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='venue',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='menu.venue', verbose_name='Заведение'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('venue', 'slug')},
        ),
    ]
