# Generated by Django 5.2.11 on 2026-08-23 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_category_venue_alter_category_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='venues',
            field=models.ManyToManyField(blank=True, related_name='categories_new', to='menu.venue', verbose_name='Заведения'),
        ),
    ]
