# Generated by Django 5.2.11 on 2026-08-23 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_create_kakao_gaudan_venue'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='venues',
            field=models.ManyToManyField(blank=True, related_name='categories', to='menu.venue', verbose_name='Заведения'),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
        migrations.RemoveField(
            model_name='category',
            name='venue',
        ),
    ]
