# Generated by Django 5.2.11 on 2026-08-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_category_venue_fk_removed'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='apple_maps_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Ссылка Apple Maps'),
        ),
        migrations.AddField(
            model_name='venue',
            name='google_maps_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Ссылка Google Maps'),
        ),
        migrations.AddField(
            model_name='venue',
            name='phone',
            field=models.CharField(blank=True, help_text='В формате +99364359786 — используется как есть в ссылке tel:', max_length=20, verbose_name='Телефон'),
        ),
    ]
